name=input('what is your name:')
print('my name is grim,',name)
a=input('Where do you live:')
print('in ukraine in the city of lviv,',a)
s=input('where are you studyin:')
print('in Lviv Polytechnic,',s)
x=input('what you like to eat:')
print('meat fruits and vegetables,',x)
d=input('what drinks do you like:')
print('tea, juice, water,',d)
h=input('you have a hobby:')
print('my hobbies ith: swimming, runnin, travelin,',h)
m=input('what is your dream:')
print('I dream of peace in Ukraine,',m)